name: Development

on:
  push:
    branches: [ "development" ]

permissions:
  contents: read

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: intl
          tools: composer
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
      - run: ./vendor/bin/phpstan analyse -c phpstan.neon --memory-limit 200M
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: intl
          tools: composer
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
      - run: ./vendor/bin/phpcs --standard=./phpcs.xml
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: intl
          tools: composer
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
      - run: ./vendor/bin/phpunit -c phpunit.xml --do-not-cache-result
  psalm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: intl
          tools: composer
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress
      - run: ./vendor/bin/psalm
